x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  splight-agent:
    image: splight-agent:latest
    container_name: splight-agent
    restart: unless-stopped
    tty: true
    entrypoint: bash
    # command: bash
    logging: *logging
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host" # TODO: remove this or move to dev mode
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.splight/agent_config:/root/.splight/agent_config
    environment:
      - LOG_LEVEL=10
      - REPORT_USAGE=true
      - PYTHONPATH=/code/src
      - COMPUTE_NODE_ID=$COMPUTE_NODE_ID
      - SPLIGHT_ACCESS_ID=$SPLIGHT_ACCESS_ID
      - SPLIGHT_SECRET_KEY=$SPLIGHT_SECRET_KEY
      - SPLIGHT_PLATFORM_API_HOST=$SPLIGHT_PLATFORM_API_HOST
      - PROCESS_TYPE=agent

