version: "3.7"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  splight-agent:
    image: splight-agent:latest
    container_name: splight-agent
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host" # TODO: remove this or move to dev mode
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.splight/agent_config:/root/.splight/agent_config
    env_file:
      - .env
    environment:
      - LOG_LEVEL=10
      - REPORT_USAGE=true
      - PYTHONPATH=/code/src
      - PROCESS_TYPE=agent

