version: "3.7"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  splight-agent:
    image: splight-agent:latest
    container_name: splight-agent
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python src/main.py
    network_mode: "host" # TODO: remove this or move to dev mode
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.splight/agent_config:/root/.splight/agent_config
    environment:
      - LOG_LEVEL=10
      
# networks:
#   splight:
#     name: splight
