[tool.poetry]
name = "splight-agent"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "splight_agent"}]

[tool.poetry.dependencies]
python = "^3.11"
splight-lib = "^3.0.8"
splight-cli = "^3.0.10"
docker = "^6.1.3"
boto3 = "^1.28.12"
ipython = "^8.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
