name: Code Quality
on: pull_request
permissions:
  contents: read
jobs:
  black:
    runs-on: ubuntu-latest
    name: Black
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: psf/black@35ea67920b7f6ac8e09be1c47278752b1e827f76 # stable
        with:
          options: "--check --diff"
          version: "23.1.0"
  isort:
    runs-on: ubuntu-latest
    name: Isort
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: isort/isort-action@754522c780bf51012c35d6e3b47a52e3900a8ed4 # master
        with:
          configuration: "--check-only --diff"
          isortVersion: "5.12.0"
  verify-version:
    runs-on: ubuntu-latest
    name: Verify version is a valid and is higher than previous version
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Save previous version
        run: |
          echo "PREVIOUS_VERSION=$(git show origin/master:pyproject.toml | grep -E 'version' | awk -F'"' '{ print $2 }')" >> "$GITHUB_ENV"
          echo "PYPROJECT_VERSION=$(grep -E 'version' pyproject.toml | awk -F'"' '{ print $2 }')" >> "$GITHUB_ENV"
          echo "INSTALL_VERSION=$(grep -E 'AGENT_VERSION=' install_scripts/install.sh | awk -F'"' '{ print $2 }')" >> "$GITHUB_ENV"
      - name: Check pyproject version changed
        run: python .github/workflows/scripts/check_versions.py ${{ env.PREVIOUS_VERSION }} lt ${{ env.PYPROJECT_VERSION }}
      - name: Check install.sh is same version as pyproject
        run: python .github/workflows/scripts/check_versions.py ${{ env.PYPROJECT_VERSION }} eq ${{ env.INSTALL_VERSION }}
